COLONNE_LABORATORI = [7,8]
COLONNE_AULE = [4,5]
COLONNE_SESSIONI = [1, 2]
COLONNE_PARAMETRI = [10,11]
INPUT_FILE_NAME="input modello.xlsx"
OUTPUT_FILE_NAME="output modello.xlsx"

#Model

MIN_DISTANCE_APPELLI = 10
SLOT_AULE = 2
SLOT_LABORATORI = 3
GUADAGNO_GIORNI_PREFERITI = 2
COSTANTE_IMPORTANZA_PRIMO_ANNO = 4
COSTANTE_IMPORTANZA_SECONDO_ANNO = 4